# This action installs dependencies necessary to compile WaterDropEngine on Linux.
# It defaults to installing all compile-critical libraries.
# ```
# - uses: ./.github/actions/install-linux-deps
# ```
# See the `inputs` section for all options and their defaults. Note that you must checkout the repository before you can use this action.
# This action will only install dependencies when the current operating system is Linux. It will do nothing on any other OS (macOS, Windows).

name: Install Linux dependencies
description: Installs the dependencies necessary to build WaterDropEngine on Linux.
inputs:
  pkg-config:
    description: Install pkg-config
    required: false
    default: "true"
  alsa:
    description: Install alsa (libasound2-dev)
    required: false
    default: "true"
  udev:
    description: Install udev (libudev-dev)
    required: false
    default: "true"
  wayland:
    description: Install Wayland (libwayland-dev)
    required: false
    default: "true"
  xkb:
    description: Install xkb (libxkbcommon-dev)
    required: false
    default: "true"
  x11:
    description: Install X11 client headers (libx11-dev)
    required: false
    default: "true"
runs:
  using: composite
  steps:
    - name: Install Linux dependencies
      shell: bash
      if: ${{ runner.os == 'Linux' }}
      run: >
        sudo apt-get update

        sudo apt-get install -y --no-install-recommends
        ${{ fromJSON(inputs['pkg-config']) && 'pkg-config' || '' }}
        ${{ fromJSON(inputs.alsa) && 'libasound2-dev' || '' }}
        ${{ fromJSON(inputs.udev) && 'libudev-dev' || '' }}
        ${{ fromJSON(inputs.wayland) && 'libwayland-dev' || '' }}
        ${{ fromJSON(inputs.xkb) && 'libxkbcommon-dev' || '' }}
        ${{ fromJSON(inputs.x11) && 'libx11-dev' || '' }}
